### ISSUE TITLE
commenting with "//"

### ISSUE THREAD

**Issue by kemazode** [vinesworth/d-nanorc#1]
Please put this line into d.nanorc:
comment "//"

**Comment by vinesworth** [comment]
Oh, sorry, I've somehow missed the issue in autumn! Seems like .nanorc syntax has been extended in recent years, and I have used neither D nor nano nor even Linux for eternity :( I'll check it ASAP.

If you happen to know anything else to fix here, like missing keywords, please let me know :)

**Comment by vinesworth** [comment]
Done, 53759c6
